name: sercrets and variables
on: 
  workflow_dispatch

jobs: 
  staging-environment:
    runs-on: ubuntu-24.04
    environment: staging
    env:

      REPO_SECRET: ${{ secrets.REPO_SECRET }}
      REPO_VAR:  ${{ vars.REPO_VAR }}

      ENV_SECRET:  ${{ secrets.ENV_SECRET }}
      ENV_VAR:  ${{ vars.ENV_VAR }}

    steps: 
     - name: inspect values inside jobs
       run: | 
         echo " Repo secret (masked):  $REPO_SECRET "
         echo " Repo variable:   $REPO_VAR "
         echo " environment secret (masked) : $ENV_SECRET "
         echo " Environment variable :  $ENV_VAR " 


  production-environment: 
    runs-on: ubuntu-24.04
    environment: production
    env:
      
      REPO_SECRET: ${{ secrets.REPO_SECRET}}
      REPO_VAR: ${{vars.REPO_VAR }}

      ENV_SECRET: ${{ secrets.ENV_SECRET }}
      ENV_VAR: ${{ vars.ENV_VAR }}

    steps: 
     - name: inspect values inside jobs
       run: |
         echo " Repo secret (masked): $REPO_SECRET "
         echo " Repo variable:  $REPO_VAR "
         echo " Environment secret (masked):  $ENV_SECRET "
         echo " environment variable: $ENV_VAR "  


